### ISSUE TITLE
REFACTOR-Schritte überarbeiten?

### ISSUE THREAD

**Issue by dgelessus** [ProPra16/programmierpraktikum-abschlussprojekt-the-avaders#2]
Wir haben auf Skype (anlässlich der Config-Umsetzung) kurz den Sinn der Schritte REFACTOR1 und REFACTOR2 diskutiert, und warum sich REFACTOR2 in der Config abschalten lässt. Dabei kamen zwei Vorschläge auf:
1. REFACTOR2 für alle Übungen anschalten (unkonfigurierbar). Das wäre weniger verwirrend für den Nutzer (warum kann man in einer Übung die Tests refactoren, und in der anderen nicht?), würde die Umsetzung der Logik vereinfachen, und hat letztendlich wenig Auswirkung auf den Ablauf einer Übung.
2. REFACTOR1 und REFACTOR2 zu einem REFACTOR-Schritt zusammenlegen. Dann lassen sich in REFACTOR sowohl normaler als auch Testcode bearbeiten, was den Ablauf vereinfacht. Selbstverständlich dürfen hier am Ende keine Compilerfehler oder fehlschlagende Tests auftreten. Man könnte sagen, dass das dem TDD-Prinzip widerspricht, aber die Benutzung des Programms erfordert ohnehin etwas Selbstdisziplin (als ob ein Info1-Student sowas hat...)

Was sagt ihr? @Batman140 @Cookiebowser @Florian-Dt

**Comment by ghost** [comment]
Option 1. finde ich gut. Das Code- und das Testrefactoring zu trennen macht Sinn da es für eine Struktur sorgt. In der Beschreibung steht auch dass man im Refactoring NUR Code refactoren darf.

**Comment by Cookiebowser** [comment]
Ich wäre auch für Option 1, oder man lässt es komplett raus, da man danach doch eh an den Tests arbeiten darf, oder?

**Comment by ghost** [comment]
Eigentlich schon. ist nur die Frage ob man nach einem Zyklus gezwungen an einem neuen test zu arbeiten oder nicht also sollen denn nach jedem Zyklus alle geschriebenen Tests verfügbar sein ? Ich mein dann könnte man doch vorherige Tests wieder entfernen oder man prüft in jedem Zyklus ob alle vorherigen tests noch vorhanden sind

**Comment by dgelessus** [comment]
Die Kata-Lib gibt die genaue Anzahl an erfolgreichen, fehlgeschlagenen und übersprungenen Tests zurück. Man könnte also zusätzliche Richtlinien festlegen, z. B. dass in RED genau ein Test dazukommen muss, und dass in REFACTOR2 keine Tests hinzugefügt oder entfernt werden dürfen.

Wobei das wiederum das Test-Refactoring behindert, da man dann keine Testcases zusammenlegen oder auseinanderziehen darf. Und wenn man nur die Anzahl an Tests betrachtet, kann man auch einfach alle Tests durch ein `assertTrue(true)` oder so ersetzen und umgeht damit den Mechanismus. Deshalb würde ich es lieber nicht erzwingen, das würde nur dazu verleiten diese Regeln zu umgehen.

**Comment by nihas101** [comment]
Ich würde zustimmen das man das Entfernen von Tests einfach zulassen sollte, sonst entstehen einfach viel zu viele neue Probleme die wir wahrscheinlich in der Zeit die wir noch haben nicht lösen können.

**Comment by Florian-Dt** [comment]
@dgelessus Option 1 ist bereits durch den [`Konfigadapter`](https://github.com/ProPra16/programmierpraktikum-abschlussprojekt-the-avaders/blob/master/src/main/java/de/hhu/propra16/avaders/konfig/KonfigAdapter.java) implementiert und die Logik bereits primitiv genug. Option 2 scheidet aus, da die Trennung zwischen Quelltext und Test damit vollständig verloren gehen würde und der Nutzer (wie bereits erwähnt wahrscheinlich ein Info1-Student) völlige Narrenfreiheit erhält.
Natürlich könnte man jeden neuen Test als eigenen Quelltext betrachten, sodass auch nur der letzte geschriebene Test verbessert werden kann. Denn das Zusammenlegen von Tests würde meiner Meinung nach auch die Regeln verletzen, da jeder neue Test auch etwas neues testen und alle Tests kleinschrittig arbeiten sollten, dass die Ursache für einen Fehlschlag leicht erkannt werden kann (Daher auch das BabySteps-Feature, die Tests so kurz zu schreiben, dass sie nach wenigen Minuten implementiert werden können).
Was man dann aber noch in einem Tests selber verbessern sollte, weiß ich nicht.

**Comment by dgelessus** [comment]
@Florian-Dt Naja, die Frage hier ist ob man die Config-Option für REFACTOR2 ganz rauswirft und dauerhaft anschaltet. Nicht nur wegen der Einfachheit des Logik-Codes (was wirklich nicht ein großes Problem ist) sondern weil es für den Nutzer und für den Schreiber der Übung verwirrend/sinnlos ist.

**Comment by ghost** [comment]
In der Hinsicht bin ich  dgelessus's  Meinung. (also vielleicht etwas unglücklich formuliert: ich meine dass es ein guter Punkt ist und finde dass wir den refactor2 aus dgelessus's genannten Gründen besser rausnehmen sollten)
