### ISSUE TITLE
Zwischenfeedback

### ISSUE THREAD

**Issue by mabre** [ProPra16/programmierpraktikum-abschlussprojekt-the-avaders#3]
Gute Nachricht zuerst: Bisher haben alle jeweils ausreichend viel beigetragen; macht weiter so, dann gibt es kein Problem mit dem Bestehen, sofern das Gesamtprojekt läuft.

Anmerkungen:
- Nur aus Interesse: ffab3b851c079b6a583d8f9750b4034c37fa6580 ist mir gerade erst aufgefallen. Was ist da passiert? Die History sieht an der Stelle etwas verknotet aus.
- Die GUI sieht schön aus (auch wenn sie momentan [zumindest auf dem `master`] glaub ich noch nicht viel kann).

**Comment by ghost** [comment]
@ffab3b8: leider hab ich an der Stelle diverse probleme mit eclipse und git gehabt. Dank intellij konnte ich diese lösen. Der masterbranch ist nun auf dem aktuellen stand der gui

**Comment by mabre** [comment]
@Batman140 @nihas101 @Florian-Dt @Cookiebowser @dgelessus bestanden
