### ISSUE TITLE
Javadoc als Systembeschreibung?

### ISSUE THREAD

**Issue by dgelessus** [ProPra16/programmierpraktikum-abschlussprojekt-the-avaders#4]
@mabre

Wir hatten geplant, die Javadocs unserer Klassen als Systembericht zu verwenden. Wäre das zusammen mit den Entwürfen aus dem `doc`-Ordner ausreichend, oder sollten wir hierzu noch ein "Hauptdokument" schreiben? Und ist es in Ordnung, wenn die Javadocs mit `./gradlew javadoc` generiert werden, oder müssen die Javadocs als generiertes HTML im Repo vorliegen?

**Comment by mabre** [comment]
Das, was ihr im doc-Ordner habt, und anständiges Javadoc würden mir reichen. Da automatisch generierte Dateien nicht committet gehören, reicht es, in der Readme zu erwähnen, wie man das Javadoc erzeugt (habt ihr ja schon drin stehen).

**Comment by dgelessus** [comment]
OK, dann stimmt das ja alles. Danke für die Antwort.
